---

- hosts: all
  become: true
  vars_files: default/vars.yml
  
  tasks: 
  - debug:
      msg: "{{ansible_distribution}}"
 
  - name: "Initiating Docker installation first..." 
    import_tasks: plays/docker-ubuntu.yml

  - name: "Creating agent and deploying Blazemeter-crane Docker containers into the machine..."
    import_tasks: plays/bm-agent.yml


